/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pahappa.systems.models;

import org.pahappa.systems.constants.Region;

/**
 *
 * @author RayGdhrt
 */
public enum ProfessionValue {

    Accountant("Accountant"),
    Actor("Actor"),
    Administrator("Administrator"),
    Aerospace_Engineer("Aerospace Engineer"),
    Agricultural_Engineer("Agricultural Engineer"),
    Anthropologist("Anthropologist"),
    Architect("Architect"),
    Astronomer("Astronomer"),
    Auditor("Auditor"),
    Banking_Analyst("Banking Analyst"),
    Bartender("Bartender"),
    Biologist("Biologist"),
    Blacksmiths("Blacksmiths"),
    Broker("Broker"),
    Buyer("Buyer"),
    Carpenter("Carpenter"),
    Chef("Chef"),
    Chemist("Chemist"),
    Childcare_Worker("Childcare Worker"),
    Civil_Engineer("Civil Engineer"),
    Clergy("Clergy"),
    Computer_Scientist("Computer Scientist"),
    Conservation_Worker("Conservation Worker"),
    Construction_Worker("Construction Worker"),
    Cook("Cook"),
    Cosmetologist("Cosmetologist"),
    Craftsperson("Craftsperson"),
    Customer_Experience_Design("Customer Experience Design"),
    Data_Analyst("Data Analyst"),
    Data_Scientist("Data Scientist"),
    Dental_Assistant("Dental Assistant"),
    Development_Manager("Development Manager"),
    Ecommerce_Seller("Ecommerce Seller"),
    Electrical_Engineer("Electrical Engineer"),
    Emergency_Medical_Technician("Emergency Medical Technician"),
    Engineer("Engineer"),
    Environmental_Engineer("Environmental Engineer"),
    Epidemiologist("Epidemiologist"),
    Event_Planner("Event Planner"),
    Farmer("Farmer"),
    Financial_Analyst("Financial Analyst"),
    Financial_Manager("Financial Manager"),
    Fishery_Worker("Fishery Worker"),
    Flight_Attendant("Flight Attendant"),
    Forestry_Worker("Forestry Worker"),
    Game_Designer("Game Designer"),
    General_Manager("General Manager"),
    Government_Worker("Government Worker"),
    Health_Educator("Health Educator"),
    Hotel_Manager("Hotel Manager"),
    Import_Export_Specialist("Import/Export Specialist"),
    Information_Design("Information Design"),
    Information_Technology_Manager("Information Technology Manager"),
    Interpreter("Interpreter"),
    Laboratory_Technician("Laboratory Technician"),
    Landscape_Architect("Landscape Architect"),
    Lawyer("Lawyer"),
    Librarian("Librarian"),
    Logistics_Engineer("Logistics Engineer"),
    Manicurists("Manicurists"),
    Manufacturing_Worker("Manufacturing Worker"),
    Mathematician("Mathematician"),
    Medical_Administration("Medical Administration"),
    Medical_Technician("Medical Technician"),
    Mental_Health_Counselor("Mental Health Counselor"),
    Miner("Miner"),
    Nanny("Nanny"),
    Nurse("Nurse"),
    Occupational_Therapist("Occupational Therapist"),
    Operations_Analyst("Operations Analyst"),
    Optometrist("Optometrist"),
    Personal_Care_Aid("Personal Care Aid"),
    Photographer("Photographer"),
    Physicist("Physicist"),
    Plumber("Plumber"),
    Politician("Politician"),
    Product_Design("Product Design"),
    Professor("Professor"),
    Project_Manager("Project Manager"),
    Property_Manager("Property Manager"),
    Purchasing_Manager("Purchasing Manager"),
    Quality_Control_Analyst("Quality Control Analyst"),
    Reporter("Reporter"),
    Restaurant_Manager("Restaurant Manager"),
    Robotics_Engineer("Robotics Engineer"),
    Sales_Manager("Sales Manager"),
    Scientist("Scientist"),
    Service_Manager("Service Manager"),
    Small_Business_Owner("Small Business Owner"),
    Sociologist("Sociologist"),
    Software_Developer("Software Developer"),
    Space_Scientist("Space Scientist"),
    Steel_Worker("Steel Worker"),
    Supervisor("Supervisor"),
    Surveyor("Surveyor"),
    Systems_Analyst("Systems Analyst"),
    Teacher("Teacher"),
    Technical_Writer("Technical Writer"),
    Technology_Architect("Technology Architect"),
    Tour_Guide("Tour Guide"),
    Transportation_Engineer("Transportation Engineer"),
    Tutor("Tutor"),
    Veterinarian("Veterinarian"),
    Waiter("Waiter"),
    Wind_Energy_Engineer("Wind Energy Engineer"),
    Zoologist("Zoologist"),
    Actuary("Actuary"),
    Advertising_Manager("Advertising Manager"),
    Agent("Agent"),
    Air_Traffic_Controller("Air Traffic Controller"),
    Archeologist("Archeologist"),
    Art_Director("Art Director"),
    Athlete("Athlete"),
    Baker("Baker"),
    Barista("Barista"),
    Bioinformatics_Scientist("Bioinformatics Scientist"),
    Biomedical_Engineer("Biomedical Engineer"),
    Board_Member("Board Member"),
    Business_Analyst("Business Analyst"),
    Captain_("naval"),
    Cashier("Cashier"),
    Chemical_Engineer("Chemical Engineer"),
    Chief_Executive("Chief Executive"),
    Choreographer("Choreographer"),
    Cleaner("Cleaner"),
    Compliance_Manager("Compliance Manager"),
    Concierge("Concierge"),
    Construction_Manager("Construction Manager"),
    Consultant("Consultant"),
    Copywriter("Copywriter"),
    Courier("Courier"),
    Curator("Curator"),
    Customer_Service("Customer Service"),
    Data_Architect("Data Architect"),
    Database_Administrator("Database Administrator"),
    Dentist("Dentist"),
    Director("Director"),
    Economist("Economist"),
    Electrician("Electrician"),
    Energy_Engineer("Energy Engineer"),
    Entrepreneur("Entrepreneur"),
    Environmental_Science("Environmental Science"),
    Equipment_Operator("Equipment Operator"),
    Executive_Management("Executive Management"),
    Fashion_Designer("Fashion Designer"),
    Financial_Controller("Financial Controller"),
    Firefighter("Firefighter"),
    Fitness_Trainer("Fitness Trainer"),
    Floral_Designer("Floral Designer"),
    Funeral_Attendant("Funeral Attendant"),
    Gardener("Gardener"),
    Geographer("Geographer"),
    Hair_Stylist("Hair Stylist"),
    Homemaker("Homemaker"),
    Human_Resources("Human Resources"),
    Industrial_Design("Industrial Design"),
    Information_Scientist("Information Scientist"),
    Installation_and_Maintenance("Installation & Maintenance"),
    Journalist("Journalist"),
    Laborer("Laborer"),
    Landscaping("Landscaping"),
    Legal_Secretary("Legal Secretary"),
    Lifeguard("Lifeguard"),
    Management_Consultant("Management Consultant"),
    Manufacturing_Engineer("Manufacturing Engineer"),
    Marketing_Analyst("Marketing Analyst"),
    Mechanical_Engineer("Mechanical Engineer"),
    Medical_Assistant("Medical Assistant"),
    Medical_Technologist("Medical Technologist"),
    Midwife("Midwife"),
    Musician("Musician"),
    Network_Administrator("Network Administrator"),
    Occupational_Health_and_Safety("Occupational Health & Safety"),
    Office_Clerk("Office Clerk"),
    Operations_Manager("Operations Manager"),
    Performance_Artist("Performance Artist"),
    Pharmacist("Pharmacist"),
    Physician("Physician"),
    Pilot("Pilot"),
    Police_Officer("Police Officer"),
    Producer("Producer"),
    Production_Manager("Production Manager"),
    Program_Manager("Program Manager"),
    Promotion_Manager("Promotion Manager"),
    Public_Relations("Public Relations"),
    Quality_Assurance_Manager("Quality Assurance Manager"),
    Railroad_Engineer("Railroad Engineer"),
    Researcher("Researcher"),
    Rigger("Rigger"),
    Sales_Engineer("Sales Engineer"),
    Salesperson("Salesperson"),
    Service_Attendant("Service Attendant"),
    Shop_Salesperson("Shop Salesperson"),
    Social_Worker("Social Worker"),
    Software_Architect("Software Architect"),
    Solar_Energy_Technician("Solar Energy Technician"),
    Statistician("Statistician"),
    Stonemason("Stonemason"),
    Surgeon("Surgeon"),
    System_Administrator("System Administrator"),
    Tailor("Tailor"),
    Technical_Support("Technical Support"),
    Technician("Technician"),
    Testing_Engineer("Testing Engineer"),
    Translator("Translator"),
    Truck_Driver("Truck Driver"),
    Urban_Design("Urban Design"),
    Visual_Designer("Visual Designer"),
    Web_Developer("Web Developer"),
    Writer("Writer");

    private String name;

    private ProfessionValue(String uiName) {
        this.name = uiName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

   
    
    public static ProfessionValue fromString(String text) {
        for (ProfessionValue b : ProfessionValue.values()) {
            if (b.name.equalsIgnoreCase(text)) {
                return b;
            }
        }
        return null;
    }
    
    

}
